### ISSUE TITLE
Kinetic and Thermodynamic parameter estimation - Equations

### ISSUE THREAD

**Issue by xenhua** [VlachosGroup/pMuTT#83]
I am interested to know the equations used by pMuTT to calculate the thermodynamic and kinetic parameters. Could you please point me to a reference which discusses these equations.

For instance, there is a book chapter by Prof. Vlachos on [microkinetic modeling of surface catalysis](https://link.springer.com/content/pdf/10.1007/978-3-319-50257-1_5-1.pdf) which lists some nice equations. How different or similar are the expressions used by pMuTT to those in the book chapter.

By the way, any updates on the opensource microkinetics tool that was supposed to be released?

Thanks.

**Comment by jonlym** [comment]
Is there a particular equation you were interested in?

All the equations should be the same except we decouple the equations since pMuTT specifies the contributions of each mode (for example, [the following function shows the equation to calculate entropy for a harmonic oscillator](https://vlachosgroup.github.io/pMuTT/statmech.html#pmutt.statmech.vib.HarmonicVib.get_SoR)). Similarly, the `Reaction` object's documentation shows how to calculate [pre-exponential factors](https://vlachosgroup.github.io/pMuTT/reactions.html#pmutt.reaction.Reaction.get_A) and [activation energies](https://vlachosgroup.github.io/pMuTT/reactions.html#pmutt.reaction.Reaction.get_EoRT_act).

Please let us know if we've omitted an equation and we'll add it to the documentation.

For the opensource MKM tool, we are still testing it but it will be showcased at the AIChE conference this year.

**Comment by xenhua** [comment]
I am interested in the expression used to calculate the rate constant of elementary reaction on the surface (Langmuir-Hinshelwood reaction) (Eq. 32 in the book chapter referenced above).

For example. the rate constant of an elementary reaction can be calculated as:

- We can use `get_A ` method of the `reaction` object to calculate the pre-exponent part. Then multiply it with the exponent of `get_EoRT_act ` method of the same object.

- The eyring rate constant can also be  calculated using product of `kB*T/h` with the exponent of `get_GoRT_act` method.

Are these two methods to calculate rate constants equivalent?

Also, I am interested in knowing the approach pMuTT uses to ensure thermodynamic consistency of the model. The book chapter referenced above suggests two methods. I believe pMuTT uses the method mentioned in section 7.2. Could you please confirm.

Thank you for giving the information about opensource MKM. I'll keep this in mind and try to plan accordingly.

**Comment by jonlym** [comment]
> Are these two methods to calculate rate constants equivalent?

We've found slight differences between the methods (discussed in Issue #42). For this reason, we have an optional parameter, `use_q` to choose between options 1 and 2.

> The book chapter referenced above suggests two methods. I believe pMuTT uses the method mentioned in section 7.2.

That's correct.

**Comment by xenhua** [comment]
If we separate out entropy part into the prefactor, the remaining part of the Gibbs free energy is the enthalpic part, which we get by the method `get_HoRT_act `of `Reaction` method. What exactly is the difference between `get_EoRT_act` and `get_HoRT_act` methods?

Also, how does pMuTT calculate the rate constants for adsorption/desorption reactions?

Thanks.

**Comment by jonlym** [comment]
The only difference between the two is [`get_EoRT_act`](https://vlachosgroup.github.io/pMuTT/reactions.html?highlight=get_eort#pmutt.reaction.Reaction.get_EoRT_act) has the change in molecularity, `del_m` as a parameter. Using this value, you can adjust the enthalpy of activation to the Arrhenius activation energy.

Currently, pMuTT does not use a different form for adsorption/desorption reactions. It always uses transition state theory.

**Comment by xenhua** [comment]
Thank you. I'll close this issue and reopen a new issue if I have any other questions.
