### ISSUE TITLE
StatMech model for a two-dimensional gas

### ISSUE THREAD

**Issue by xenhua** [VlachosGroup/pMuTT#84]
I see that there is a **Harmonic Approximation (harmonic)** preset to model adsorbates in general. This preset only considers `vib_model ` with `HarmonicVib model.`
However, I would like to model a weakly adsorbed adsorbate as a 2-d gas, which retains its full rotational as well as vibrational modes. How can I model the `StatMech` model of a weakly adsorbing adsorbate? 

Issue # [48 ](https://github.com/VlachosGroup/pMuTT/issues/48) discusses the specification of individual `StatMech` models for translational, rotational, vibrational and electronic modes while reading species from excel sheet. Issue #49 addresses this issue as solved.

However, when I am trying to model a 2-d gas with `HarmonicVib`, `RigidRotor` and `elec_model` in separate columns rather than using `Harmonic` preset, I am not able to read the excel sheet.

```
Traceback (most recent call last):
  File "new_script.py", line 38, in <module>
    specie = Nasa.from_statmech(T_low=T_low, T_high=T_high, references=refs, **specie_data)
TypeError: from_statmech() missing 1 required positional argument: 'statmech_model'

```

**Comment by jonlym** [comment]
My guess is that you need to pass the `StatMech` class to `from_statmech` (since the presets does this for you automatically). Could you try inserting this into your code?

```python
from pmutt.statmech import StatMech

# Replace line 38 with this where StatMech is passed explicitly
specie = Nasa.from_statmech(T_low=T_low, T_high=T_high, references=refs, statmech_model=StatMech, **specie_data)
```
If that does not work, I would need to see your spreadsheet.

**Comment by xenhua** [comment]
Including `statmech_model=StatMech,` gives me a new error in `get_CpoR`. 

```
Traceback (most recent call last):
  File "new_script.py", line 21, in <module>
    specie = Nasa.from_statmech(T_low=T_low, T_high=T_high, statmech_model=StatMech, **specie_data)
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/pMuTT/empirical/nasa.py", line 496, in from_statmech
    CpoR = np.array([statmech_model.get_CpoR(T=T_i) for T_i in T])
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/pMuTT/empirical/nasa.py", line 496, in <listcomp>
    CpoR = np.array([statmech_model.get_CpoR(T=T_i) for T_i in T])
  File "/home/xenhua/.local/lib/python3.6/site-packages/pmutt/statmech/__init__.py", line 519, in get_CpoR
    **kwargs)
  File "/home/xenhua/.local/lib/python3.6/site-packages/pmutt/statmech/__init__.py", line 336, in get_quantity
    **specie_kwargs),
  File "/home/xenhua/.local/lib/python3.6/site-packages/pmutt/__init__.py", line 580, in _get_mode_quantity
    raise e
  File "/home/xenhua/.local/lib/python3.6/site-packages/pmutt/__init__.py", line 577, in _get_mode_quantity
    method = getattr(mode, method_name)
AttributeError: 'str' object has no attribute 'get_CpoR'
```
I am also attaching my spreadsheet here. Thanks.
[species.xlsx](https://github.com/VlachosGroup/pMuTT/files/3530252/species.xlsx)
[new_script.py.txt](https://github.com/VlachosGroup/pMuTT/files/3530268/new_script.py.txt)

**Comment by jonlym** [comment]
Thank you for the script and spreadsheet.

The bug about the `StatMech` model is still an issue that will be fixed in the next version (thank you for pointing it out). However, I found some errors in the spreadsheet and script (I've highlighted all the changes I made in the spreadsheet in red and added comment blocks around the changes to the script).

**Import statements in script**
I noticed your import statements to pMuTT have mixed case (whereas it should be all lower case). For example:
> from pMuTT.io.excel import read_excel

This means you are using an older version and you should update it and uninstall the previous version.

**Corrections to vib_model column in spreadsheet**
Minor typos

**Missing information for rotational model**
If you would like to use [`RigidRotor`](https://vlachosgroup.github.io/pMuTT/statmech.html#pmutt.statmech.rot.RigidRotor) as your rotational model, there are three required parameters:
- `symmetrynumber`
- `geometry`
- `rot_temperatures`

The `symmetrynumber` has to be specified by its own column. The `geometry` and `rot_temperatures` can either have their own columns or you supply a file that can be read by [ASE](https://wiki.fysik.dtu.dk/ase/) in the atoms column.

The edited files are below:
[species.xlsx](https://github.com/VlachosGroup/pMuTT/files/3530493/species.xlsx)
[new_script_JL.py.txt](https://github.com/VlachosGroup/pMuTT/files/3530495/new_script_JL.py.txt)

Let me know if this addresses your issue.

**Comment by xenhua** [comment]
Thanks Jon so much for pointing out the errors in my code and spreadsheet.

I see that you have fixed this issue and updated pmutt to version 1.2.12.
I have updated my pmutt (at home) to the latest version and I could now run this spreadsheet with your modified script. I'll update pmutt also on my office system.

**Comment by jonlym** [comment]
I realized I didn't answer your question about modeling a 2D gas. The translational mode should be set to [`IdealTrans`](https://vlachosgroup.github.io/pMuTT/statmech.html#pmutt.statmech.trans.FreeTrans) as you did with the other modes. It requires two parameters:
- n_degrees (relevant species would have a value of 2)
- molecular_weight (in g/mol or you can pass an ASE Atoms object as discussed above)
